sonar.projectKey=CT5192-LMS-Frontend
sonar.projectName=LMS Frontend (React)
sonar.organization=93f15e91ea0a887a662864dd5bbf46c3c089d941
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/build/**
